development:
  adapter: postgresql
  encoding: utf8
  database: background_benchmarks_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: background_benchmarks_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: background_benchmarks_production
  pool: 5
  username: 
  password:
